environment:
  matrix:
  fast_finish: true
  - os: Visual Studio 2015
  - os: Windows Server 2012 R2  

init:
  - git config --global core.autocrlf input

build:
  verbosity: detailed

before_build:
  - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
build_script:
  - cmd: build.cmd
test: off
version: 0.0.1.{build}
artifacts:
  - path: build\fable
    name: fable
  
 